export interface JuniperSrxApplication {
  name: string;
  description: string;
  protocol: string;
  port: string;
}

export const defaultApplications: JuniperSrxApplication[] = [
  { name: "junos-http", description: "Hypertext Transfer Protocol", protocol: "tcp", port: "80" },
  { name: "junos-https", description: "Hypertext Transfer Protocol over SSL", protocol: "tcp", port: "443" },
  { name: "junos-ssh", description: "Secure Shell", protocol: "tcp", port: "22" },
  { name: "junos-telnet", description: "Telnet", protocol: "tcp", port: "23" },
  { name: "junos-ftp", description: "File Transfer Protocol", protocol: "tcp", port: "21" },
  { name: "junos-tftp", description: "Trivial File Transfer Protocol", protocol: "udp", port: "69" },
  { name: "junos-dns-tcp", description: "Domain Name Service over TCP", protocol: "tcp", port: "53" },
  { name: "junos-dns-udp", description: "Domain Name Service over UDP", protocol: "udp", port: "53" },
  { name: "junos-ntp", description: "Network Time Protocol", protocol: "udp", port: "123" },
  { name: "junos-snmp-request", description: "SNMP request", protocol: "udp", port: "161" },
  { name: "junos-snmp-trap", description: "SNMP trap", protocol: "udp", port: "162" },
  { name: "junos-ldap", description: "Lightweight Directory Access Protocol", protocol: "tcp", port: "389" },
  { name: "junos-ldaps", description: "LDAP over SSL", protocol: "tcp", port: "636" },
  { name: "junos-radius", description: "Remote Authentication Dial-In User Service", protocol: "udp", port: "1812, 1813, 1645, 1646" },
  { name: "junos-tacacs", description: "Terminal Access Controller Access-Control System", protocol: "tcp", port: "49" },
  { name: "junos-ike", description: "Internet Key Exchange", protocol: "udp", port: "500" },
  { name: "junos-ike-nat", description: "IKE with NAT Traversal", protocol: "udp", port: "4500" },
  { name: "junos-ping", description: "Ping utility", protocol: "icmp", port: "any" },
  { name: "junos-traceroute", description: "Traceroute utility", protocol: "udp", port: "33434-33534" },
  { name: "junos-smtp", description: "Simple Mail Transfer Protocol", protocol: "tcp", port: "25" },
  { name: "junos-smtps", description: "SMTP over SSL", protocol: "tcp", port: "465" },
  { name: "junos-pop3", description: "Post Office Protocol version 3", protocol: "tcp", port: "110" },
  { name: "junos-pop3s", description: "POP3 over SSL", protocol: "tcp", port: "995" },
  { name: "junos-imap", description: "Internet Message Access Protocol", protocol: "tcp", port: "143" },
  { name: "junos-imaps", description: "IMAP over SSL", protocol: "tcp", port: "993" },
  { name: "junos-sql-net", description: "Oracle SQL*Net", protocol: "tcp", port: "1521" },
  { name: "junos-mysql", description: "MySQL Database", protocol: "tcp", port: "3306" },
  { name: "junos-ms-rpc", description: "Microsoft RPC", protocol: "tcp", port: "135" },
  { name: "junos-ms-sql", description: "Microsoft SQL Server", protocol: "tcp", port: "1433" },
  { name: "junos-netbios-session", description: "NetBIOS Session Service", protocol: "tcp", port: "139" },
  { name: "junos-smb", description: "Server Message Block", protocol: "tcp", port: "445" },
  { name: "junos-rtsp", description: "Real Time Streaming Protocol", protocol: "tcp, udp", port: "554" },
  { name: "junos-sip", description: "Session Initiation Protocol", protocol: "tcp, udp", port: "5060" },
  { name: "junos-sips", description: "SIP over TLS", protocol: "tcp", port: "5061" },
  { name: "junos-h323", description: "H.323 Call Signaling", protocol: "tcp", port: "1720" },
  { name: "junos-pptp", description: "Point-to-Point Tunneling Protocol", protocol: "tcp", port: "1723" },
  { name: "junos-l2tp", description: "Layer 2 Tunneling Protocol", protocol: "udp", port: "1701" },
  { name: "junos-esp", description: "IPSec Encapsulating Security Payload", protocol: "esp", port: "any" },
  { name: "junos-ah", description: "IPSec Authentication Header", protocol: "ah", port: "any" },
  { name: "junos-gre", description: "Generic Routing Encapsulation", protocol: "gre", port: "any" },
  { name: "junos-ospf", description: "Open Shortest Path First", protocol: "ospf", port: "any" },
  { name: "junos-bgp", description: "Border Gateway Protocol", protocol: "tcp", port: "179" },
  { name: "junos-rip", description: "Routing Information Protocol", protocol: "udp", port: "520" },
  { name: "junos-dhcp-client", description: "DHCP Client", protocol: "udp", port: "68" },
  { name: "junos-dhcp-server", description: "DHCP Server", protocol: "udp", port: "67" },
  { name: "junos-vnc", description: "Virtual Network Computing", protocol: "tcp", port: "5900-5909" },
  { name: "junos-rdp", description: "Remote Desktop Protocol", protocol: "tcp", port: "3389" },
  { name: "any-tcp", description: "Any TCP traffic", protocol: "tcp", port: "any" },
  { name: "any-udp", description: "Any UDP traffic", protocol: "udp", port: "any" },
  { name: "any-icmp", description: "Any ICMP traffic", protocol: "icmp", port: "any" },
];
