export interface JuniperSrxApplication {
  name: string;
  description: string;
  protocol: string;
  port: string;
}

export const defaultApplications: JuniperSrxApplication[] = [
  {
    name: "junos-ftp",
    description: "File Transfer Protocol (FTP)",
    protocol: "tcp",
    port: "21",
  },
  {
    name: "junos-ftp-data",
    description: "(Trivial) File Transfer Protocol (TFTP) Data",
    protocol: "tcp",
    port: "20",
  },
  {
    name: "junos-tftp",
    description: "Trivial File Transfer Protocol (TFTP)",
    protocol: "udp",
    port: "69",
  },
  {
    name: "junos-twamp",
    description: "Two-Way Active Measurement Protocol (TWAMP)",
    protocol: "tcp",
    port: "862",
  },
  {
    name: "junos-rtsp",
    description: "Real Time Streaming Protocol (RTSP)",
    protocol: "tcp",
    port: "554",
  },
  {
    name: "junos-netbios-session",
    description: "Network Basic Input Output System  - networking protocol used on Windows networks session service port",
    protocol: "tcp",
    port: "139",
  },
  {
    name: "junos-smb-session",
    description: "",
    protocol: "tcp",
    port: "445",
  },
  {
    name: "junos-ssh",
    description: "",
    protocol: "tcp",
    port: "22",
  },
  {
    name: "junos-telnet",
    description: "",
    protocol: "tcp",
    port: "23",
  },
  {
    name: "junos-smtp",
    description: "",
    protocol: "tcp",
    port: "25",
  },
  {
    name: "junos-tacacs",
    description: "TACACS Database Service",
    protocol: "tcp",
    port: "49",
  },
  {
    name: "junos-tacacs-ds",
    description: "",
    protocol: "tcp",
    port: "65",
  },
  {
    name: "junos-dhcp-client",
    description: "",
    protocol: "udp",
    port: "68",
  },
  {
    name: "junos-dhcp-server",
    description: "",
    protocol: "udp",
    port: "67",
  },
  {
    name: "junos-bootpc",
    description: "",
    protocol: "udp",
    port: "68",
  },
  {
    name: "junos-bootps",
    description: "",
    protocol: "udp",
    port: "67",
  },
  {
    name: "junos-finger",
    description: "",
    protocol: "tcp",
    port: "79",
  },
  {
    name: "junos-http",
    description: "",
    protocol: "tcp",
    port: "80",
  },
  {
    name: "junos-https",
    description: "",
    protocol: "tcp",
    port: "443",
  },
  {
    name: "junos-pop3",
    description: "",
    protocol: "tcp",
    port: "110",
  },
  {
    name: "junos-pop3s",
    description: "",
    protocol: "tcp",
    port: "995",
  },
  {
    name: "junos-ident",
    description: "",
    protocol: "tcp",
    port: "113",
  },
  {
    name: "junos-nntp",
    description: "",
    protocol: "tcp",
    port: "119",
  },
  {
    name: "junos-ntp",
    description: "",
    protocol: "udp",
    port: "123",
  },
  {
    name: "junos-imap",
    description: "",
    protocol: "tcp",
    port: "143",
  },
  {
    name: "junos-imaps",
    description: "",
    protocol: "tcp",
    port: "993",
  },
  {
    name: "junos-bgp",
    description: "",
    protocol: "tcp",
    port: "179",
  },
  {
    name: "junos-ldap",
    description: "",
    protocol: "tcp",
    port: "389",
  },
  {
    name: "junos-snpp",
    description: "",
    protocol: "tcp",
    port: "444",
  },
  {
    name: "junos-biff",
    description: "",
    protocol: "udp",
    port: "512",
  },
  {
    name: "junos-who",
    description: "UNIX who",
    protocol: "udp",
    port: "513",
  },
  {
    name: "junos-syslog",
    description: "",
    protocol: "udp",
    port: "514",
  },
  {
    name: "junos-printer",
    description: "line printer daemon, printer, spooler",
    protocol: "tcp",
    port: "515",
  },
  {
    name: "junos-rip",
    description: "",
    protocol: "udp",
    port: "520",
  },
  {
    name: "junos-radius",
    description: "INA sanctioned RADIUS port numbers",
    protocol: "udp",
    port: "1812",
  },
  {
    name: "junos-radacct",
    description: "",
    protocol: "udp",
    port: "1813",
  },
  {
    name: "junos-nfsd-tcp",
    description: "",
    protocol: "tcp",
    port: "2049",
  },
  {
    name: "junos-nfsd-udp",
    description: "",
    protocol: "udp",
    port: "2049",
  },
  {
    name: "junos-cvspserver",
    description: "",
    protocol: "tcp",
    port: "2401",
  },
  {
    name: "junos-ldp-tcp",
    description: "Label Distribution Protocol",
    protocol: "tcp",
    port: "646",
  },
  {
    name: "junos-ldp-udp",
    description: "",
    protocol: "udp",
    port: "646",
  },
  {
    name: "junos-xnm-ssl",
    description: "JUNOScript and JUNOScope management (over SSL)",
    protocol: "tcp",
    port: "3220",
  },
  {
    name: "junos-xnm-clear-text",
    description: "JUNOScript and JUNOScope management (clear text)",
    protocol: "tcp",
    port: "3221",
  },
  {
    name: "junos-ike",
    description: "IPSec tunnel",
    protocol: "udp",
    port: "500",
  },
  {
    name: "any",
    description: "Any IPv4 application ",
    protocol: "any",
    port: "any",
  },
  {
    name: "junos-aol",
    description: "America Online instant messaging services",
    protocol: "tcp",
    port: "5190-5193",
  },
  {
    name: "junos-chargen",
    description: "Character generator protocol",
    protocol: "udp",
    port: "19",
  },
  {
    name: "junos-dhcp-relay",
    description: "DHCP Relay services",
    protocol: "udp",
    port: "67",
  },
  {
    name: "junos-discard",
    description: "Discard  protocol",
    protocol: "udp",
    port: "9",
  },
  {
    // it uses ALG, but I dont know yet how to represent that here
    name: "junos-dns-udp",
    description: "Domain Name System (DNS) over UDP",
    protocol: "udp",
    port: "53",
  },
  {
    // it uses ALG, but I dont know yet how to represent that here
    name: "junos-dns-tcp",
    description: "Domain Name System (DNS) over TCP",
    protocol: "tcp",
    port: "53",
  },
  {
    name: "junos-echo",
    description: "Echo protocol",
    protocol: "udp",
    port: "7",
  },
  {
    name: "junos-gopher",
    description: "Gopher internet protocol",
    protocol: "tcp",
    port: "70",
  },
  {
    name: "junos-gtp",
    description: "GPRS Tunneling Protocol UDP",
    protocol: "udp",
    port: "2123",
  },
  {
    name: "junos-gnutella",
    description: "Gnutella File Sharing Protocol",
    protocol: "udp",
    port: "6346-6347",
  },
  {
    name: "junos-gre",
    description: "Generic Routing Encapsulation Protocol",
    protocol: "gre",
    port: "None",
  },
  {
    name: "junos-http-ext",
    description: "HTTP extension",
    protocol: "tcp",
    port: "7001",
  },
  {
    name: "junos-icmp-all",
    description: "ICMP All Traffic: This can be made to be more restrictive by specifying icmp type and code",
    protocol: "icmp",
    port: "None",
  },
  {
    name: "junos-icmp-ping",
    description: "ICMP Ping: The echo-reply is allowed upon return",
    protocol: "icmp",
    port: "echo-request",
  },
  {
    name: "junos-internet-locator-service",
    description: "Internet locator service",
    protocol: "tcp",
    port: "389",
  },
  {
    name: "junos-ike-nat",
    description: "IKE protocol",
    protocol: "udp",
    port: "4500",
  },
  {
    name: "junos-irc",
    description: "Internet Relay Chat protocol",
    protocol: "tcp",
    port: "6660-6669",
  },
  {
    name: "junos-l2tp",
    description: "L2TP tunnelng protocol",
    protocol: "udp",
    port: "1701",
  },
  {
    name: "junos-lpr",
    description: "Line Printer Daemon protocol",
    protocol: "tcp",
    port: "515",
  },
  {
    name: "junos-mail",
    description: "Mail (SMTP) protocol",
    protocol: "tcp",
    port: "25",
  },
  {
    // it uses ALG, but I dont know yet how to represent that here
    name: "junos-h323",
    description: "H.323 Protocol for audio/video conferencing",
    protocol: "Multiple (tcp/udp)",
    port: "1720, 1719, 1503, 289, 522, 1731",
  },
  {
    // it uses ALG, but I dont know yet how to represent that here
    name: "junos-mgcp-ua",
    description: "MGCP Protocol",
    protocol: "udp",
    port: "2427",
  },
  {
    name: "junos-mgcp-ca",
    description: "MGCP Protocol",
    protocol: "udp",
    port: "2727",
  },
  {
    name: "junos-msn",
    description: "Microsoft Network Messenger",
    protocol: "tcp",
    port: "1863",
  },
  {
    // it uses ALG, but I dont know yet how to represent that here
    name: "junos-ms-rpc-tcp",
    description: "Microsoft RPC",
    protocol: "tcp",
    port: "135",
  },
  {
    // it uses ALG, but I dont know yet how to represent that here
    name: "junos-ms-rpc-udp",
    description: "Microsoft RPC",
    protocol: "udp",
    port: "135",
  },
  {
    name: "junos-ms-rpc-epm",
    description: "Microsoft RPC EPM (End Point Mapper)",
    protocol: "tcp",
    port: "None",
  },
  {
    name: "junos-ms-rpc-msexchange-directory-rfr",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-msexchange-info-store",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-msexchange-directory-nsp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-wmic-admin",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-wmic-webm-level1login",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-wmic-webm-objectsink",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-wmic-webm-services",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-wmic-webm-callresult",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-wmic-webm-login-clientid",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-wmic-webm-login-helper",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-wmic-webm-refreshing-services",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-wmic-webm-remote-refresher",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-wmic-webm-shutdown",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-wmic-webm-classobject",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-wmic-admin2",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-wmic-mgmt",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-iis-com-1",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-iis-com-adminbase",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-uuid-any-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-rpc-uuid-any-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-ms-sql",
    description: "Microsoft SQL",
    protocol: "tcp",
    port: "1433",
  },
  {
    name: "junos-nbname",
    description: "NetBIOS Name Service",
    protocol: "udp",
    port: "137",
  },
  {
    name: "junos-nbds",
    description: "NetBIOS Datagram Service",
    protocol: "udp",
    port: "138",
  },
  {
    name: "junos-nfs",
    description: "Network File System  protocol",
    protocol: "udp",
    port: "111",
  },
  {
    name: "junos-ns-global",
    description: "NS-Global (Management protocol for Juniper Networks Firewall/VPN devices)",
    protocol: "tcp",
    port: "15397",
  },
  {
    name: "junos-ns-global-pro",
    description: "NS-Global-PRO (Monitoring system for the Juniper Networks Firewall/VPN devices)",
    protocol: "tcp",
    port: "15397",
  },
  {
    name: "junos-nsm",
    description: "NetScreen Security Manager",
    protocol: "udp",
    port: "69",
  },
  {
    name: "junos-ospf",
    description: "OSPF protocol",
    protocol: "ospf",
    port: "None",
  },
  {
    name: "junos-pc-anywhere",
    description: "PC-anywhere remote control and file transfer protocol",
    protocol: "udp",
    port: "5632",
  },
  {
    name: "junos-ping",
    description: "Ping protocol",
    protocol: "icmp",
    port: "None",
  },
  {
    name: "junos-pingv6",
    description: "Ping for IPv6",
    protocol: "ipv6-icmp",
    port: "None",
  },
  {
    name: "junos-icmp6-dst-unreach-addr",
    description: "",
    protocol: "ipv6-icmp",
    port: "icmp6-code 3",
  },
  {
    name: "junos-icmp6-dst-unreach-admin",
    description: "",
    protocol: "ipv6-icmp",
    port: "icmp6-code 1",
  },
  {
    name: "junos-icmp6-dst-unreach-beyond",
    description: "",
    protocol: "ipv6-icmp",
    port: "icmp6-code 2",
  },
  {
    name: "junos-icmp6-dst-unreach-port",
    description: "",
    protocol: "ipv6-icmp",
    port: "icmp6-code 4",
  },
  {
    name: "junos-icmp6-dst-unreach-route",
    description: "",
    protocol: "ipv6-icmp",
    port: "icmp6-code 0",
  },
  {
    name: "junos-icmp6-echo-reply",
    description: "",
    protocol: "ipv6-icmp",
    port: "icmp6-type 129",
  },
  {
    name: "junos-icmp6-echo-request",
    description: "",
    protocol: "ipv6-icmp",
    port: "icmp6-type 128",
  },
  {
    name: "junos-icmp6-packet-too-big",
    description: "",
    protocol: "ipv6-icmp",
    port: "None",
  },
  {
    name: "junos-icmp6-param-prob-header",
    description: "",
    protocol: "ipv6-icmp",
    port: "None",
  },
  {
    name: "junos-icmp6-param-prob-nexthdr",
    description: "",
    protocol: "ipv6-icmp",
    port: "None",
  },
  {
    name: "junos-icmp6-param-prob-option",
    description: "",
    protocol: "ipv6-icmp",
    port: "None",
  },
  {
    name: "junos-icmp6-time-exceed-reassembly",
    description: "",
    protocol: "ipv6-icmp",
    port: "None",
  },
  {
    name: "junos-icmp6-time-exceed-transit",
    description: "",
    protocol: "ipv6-icmp",
    port: "None",
  },
  {
    name: "junos-icmp6-all",
    description: "",
    protocol: "ipv6-icmp",
    port: "None",
  },
  {
    name: "junos-pptp",
    description: "",
    protocol: "None",
    port: "1723",
  },
  {
    name: "junos-realaudio",
    description: "",
    protocol: "None",
    port: "554",
  },
  {
    name: "junos-sccp",
    description: "",
    protocol: "None",
    port: "2000",
  },
  {
    name: "junos-sctp-any",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sip",
    description: "",
    protocol: "None",
    port: "5060",
  },
  {
    name: "junos-rsh",
    description: "",
    protocol: "None",
    port: "514",
  },
  {
    name: "junos-smb",
    description: "",
    protocol: "None",
    port: "139",
  },
  {
    name: "junos-sql-monitor",
    description: "",
    protocol: "None",
    port: "1434",
  },
  {
    name: "junos-sqlnet-v1",
    description: "",
    protocol: "None",
    port: "1525",
  },
  {
    name: "junos-sqlnet-v2",
    description: "",
    protocol: "None",
    port: "1521",
  },
  {
    name: "junos-sun-rpc-tcp",
    description: "",
    protocol: "None",
    port: "111",
  },
  {
    name: "junos-sun-rpc-udp",
    description: "",
    protocol: "None",
    port: "111",
  },
  {
    name: "junos-sun-rpc-portmap-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-portmap-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-nfs-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-nfs-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-mountd-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-mountd-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-ypbind-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-ypbind-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-status-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-status-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-ypserv-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-ypserv-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-rquotad-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-rquotad-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-nlockmgr-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-nlockmgr-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-ruserd-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-ruserd-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-sadmind-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-sadmind-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-sprayd-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-sprayd-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-walld-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-walld-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-any-tcp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-sun-rpc-any-udp",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-talk",
    description: "",
    protocol: "None",
    port: "517",
  },
  {
    name: "junos-ntalk",
    description: "",
    protocol: "None",
    port: "518",
  },
  {
    name: "junos-r2cp",
    description: "",
    protocol: "None",
    port: "28672",
  },
  {
    name: "junos-tcp-any",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-udp-any",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-uucp",
    description: "",
    protocol: "None",
    port: "540",
  },
  {
    name: "junos-vdo-live",
    description: "",
    protocol: "None",
    port: "7000-7010",
  },
  {
    name: "junos-vnc",
    description: "",
    protocol: "None",
    port: "5800",
  },
  {
    name: "junos-wais",
    description: "",
    protocol: "None",
    port: "210",
  },
  {
    name: "junos-whois",
    description: "",
    protocol: "None",
    port: "43",
  },
  {
    name: "junos-winframe",
    description: "",
    protocol: "None",
    port: "1494",
  },
  {
    name: "junos-x-windows",
    description: "",
    protocol: "None",
    port: "6000-6063",
  },
  {
    name: "junos-ymsg",
    description: "",
    protocol: "None",
    port: "5000-5010",
  },
  {
    name: "junos-wxcontrol",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-snmp-agentx",
    description: "",
    protocol: "None",
    port: "None",
  },
  {
    name: "junos-stun",
    description: "",
    protocol: "None",
    port: "3478-3479",
  },
  {
    name: "junos-persistent-nat",
    description: "",
    protocol: "None",
    port: "65535",
  },
  {
    name: "junos-smtps",
    description: "",
    protocol: "None",
    port: "587",
  },
  {
    name: "junos-rdp",
    description: "",
    protocol: "None",
    port: "3389",
  },
  {
    name: "junos-vxlan",
    description: "",
    protocol: "udp",
    port: "4789",
  },
];
