name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "25"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.0.9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Typechecks
        run: pnpm run typecheck

      - name: Run Linter
        run: pnpm run lint

      - name: Run knip
        run: pnpm dlx knip
        
      - name: Run Build
        run: pnpm run build